### ISSUE TITLE
Hide all other traces of Backdrop in the output of the HTML-code

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/remove_generator#1]
In the light of the quote from the modules description:

> 
In the remediation advice, OWASP recommends removing HTML code or anything else that explicitly points to a specific framework to be sure the framework cannot be detected by automatic scans.

I wonder if the module also could take care of hiding several other hints to Backdrop in the HTML-code:

`@import url("https://www.domain.tld/core/themes/basis/css/component/backdrop-form.css?qlm1ff");`

` <script>window.Backdrop = {settings: {"basePath":"\/","pathPrefix":"","drupalCompatibility":true,"ajaxPageState":`

`<script src="https://www.domain.tld/core/misc/backdrop.js?v=1.17.4"></script>`

**Comment by deekayen** [comment]
Nope
